packages:
  - apps/*
  - packages/*
catalog:
  "@ai-sdk/openai": ^1.0.8
  "@arcjet/next": 1.0.0-alpha.34
  "@auto-it/all-contributors": ^11.3.0
  "@auto-it/first-time-contributor": ^11.3.0
  "@biomejs/biome": ^1.9.4
  "@chromatic-com/storybook": ^3.2.2
  "@clerk/nextjs": ^6.8.3
  "@clerk/themes": ^2.1.55
  "@clerk/types": ^4.39.2
  "@content-collections/cli": ^0.1.6
  "@content-collections/core": ^0.7.3
  "@content-collections/mdx": ^0.2.0
  "@content-collections/next": ^0.2.4
  "@hookform/resolvers": ^3.9.1
  "@liveblocks/client": ^2.13.1
  "@liveblocks/node": ^2.13.1
  "@liveblocks/react": ^2.13.1
  "@logtail/next": ^0.1.7
  "@neondatabase/serverless": ^0.10.4
  "@next/bundle-analyzer": ^15.1.0
  "@next/third-parties": ^15.1.0
  "@prisma/adapter-neon": ^6.0.1
  "@prisma/client": ^6.0.1
  "@prisma/nextjs-monorepo-workaround-plugin": ^6.0.1
  "@radix-ui/react-accordion": ^1.2.1
  "@radix-ui/react-alert-dialog": ^1.1.2
  "@radix-ui/react-aspect-ratio": ^1.1.0
  "@radix-ui/react-avatar": ^1.1.1
  "@radix-ui/react-checkbox": ^1.1.2
  "@radix-ui/react-collapsible": ^1.1.1
  "@radix-ui/react-context-menu": ^2.2.2
  "@radix-ui/react-dialog": ^1.1.2
  "@radix-ui/react-dropdown-menu": ^2.1.2
  "@radix-ui/react-hover-card": ^1.1.2
  "@radix-ui/react-icons": ^1.3.2
  "@radix-ui/react-label": ^2.1.0
  "@radix-ui/react-menubar": ^1.1.2
  "@radix-ui/react-navigation-menu": ^1.2.1
  "@radix-ui/react-popover": ^1.1.2
  "@radix-ui/react-progress": ^1.1.0
  "@radix-ui/react-radio-group": ^1.2.1
  "@radix-ui/react-scroll-area": ^1.2.1
  "@radix-ui/react-select": ^2.1.2
  "@radix-ui/react-separator": ^1.1.0
  "@radix-ui/react-slider": ^1.2.1
  "@radix-ui/react-slot": ^1.1.0
  "@radix-ui/react-switch": ^1.1.1
  "@radix-ui/react-tabs": ^1.1.1
  "@radix-ui/react-toast": ^1.2.2
  "@radix-ui/react-toggle": ^1.1.0
  "@radix-ui/react-toggle-group": ^1.1.0
  "@radix-ui/react-tooltip": ^1.1.4
  "@react-email/components": 0.0.31
  "@sentry/nextjs": ^8.43.0
  "@storybook/addon-essentials": ^8.4.7
  "@storybook/addon-interactions": ^8.4.7
  "@storybook/addon-onboarding": ^8.4.7
  "@storybook/addon-themes": ^8.4.7
  "@storybook/blocks": ^8.4.7
  "@storybook/nextjs": ^8.4.7
  "@storybook/react": ^8.4.7
  "@storybook/test": ^8.4.7
  "@stripe/agent-toolkit": ^0.2.0
  "@t3-oss/env-nextjs": ^0.11.1
  "@tailwindcss/typography": ^0.5.15
  "@testing-library/dom": ^10.4.0
  "@testing-library/react": ^16.1.0
  "@turbo/gen": ^2.3.3
  "@types/lodash.merge": ^4.6.9
  "@types/node": ^22
  "@types/react": ^19
  "@types/react-dom": ^19
  "@types/ws": ^8.5.13
  "@vercel/analytics": ^1.4.1
  "@vercel/blob": ^0.27.0
  "@vercel/flags": ^2.6.3
  "@vercel/toolbar": ^0.1.28
  "@vitejs/plugin-react": ^4.3.4
  "ai": ^4.0.14
  "autoprefixer": ^10.4.20
  bufferutil: ^4.0.8
  chalk: ^5.3.0
  chromatic: ^11.20.0
  "class-variance-authority": ^0.7.1
  clsx: ^2.1.1
  cmdk: ^1.0.4
  commander: ^12.1.0
  concurrently: ^9.1.0
  date-fns: ^4.1.0
  embla-carousel-react: ^8.5.1
  fumadocs-core: ^14.6.0
  fuse.js: ^7.0.0
  geist: ^1.3.1
  import-in-the-middle: ^1.11.3
  input-otp: ^1.4.1
  jsdom: ^25.0.1
  lodash.merge: ^4.6.2
  lucide-react: ^0.468.0
  mdx-bundler: ^10.0.3
  next: ^15.1.0
  next-secure-headers: ^2.2.0
  next-themes: ^0.4.4
  postcss: ^8
  posthog-js: ^1.195.0
  posthog-node: ^4.3.1
  prisma: ^6.0.1
  react: ^19.0.0
  react-day-picker: ^8.10.1
  react-dom: ^19.0.0
  react-email: ^3.0.4
  react-hook-form: ^7.54.0
  react-markdown: ^9.0.1
  react-moveable: ^0.56.0
  react-resizable-panels: ^2.1.7
  react-wrap-balancer: ^1.1.1
  reading-time: ^1.5.0
  recharts: ^2.15.0
  require-in-the-middle: ^7.4.0
  resend: ^4.0.1
  schema-dts: ^1.1.2
  server-only: ^0.0.1
  sharp: ^0.33.5
  shiki: ^1.24.2
  sonner: ^1.7.1
  sqip: 1.0.0-alpha.51
  sqip-plugin-data-uri: 1.0.0-alpha.52
  sqip-plugin-primitive: 1.0.0-alpha.53
  sqip-plugin-svgo: 1.0.0-alpha.54
  storybook: ^8.4.7
  stripe: ^17.4.0
  supabase: ^2.0.0
  svix: ^1.44.0
  syncpack: 14.0.0-alpha.1
  tailwind-merge: ^2.5.5
  tailwindcss: ^3.4.16
  tailwindcss-animate: ^1.0.7
  turbo: ^2.3.3
  typescript: ^5.7.2
  ultracite: ^4.1.11
  undici: ^7.1.0
  vaul: ^1.1.1
  vitest: ^2.1.8
  ws: ^8.18.0
  zod: ^3.24.0
